Repository terrifricker/recall-group, pull requests merged in 2021-08, with the labels that each got.

#4 added script tag to index head section
  index.html
Labels: good first issue

#17 Update README.md
  README.md
Labels: documentation

#23 Meta tag
  index.html
  planet-facts-snippet.html
Labels: bug
